# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'LocalTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocalTool
  pod 'YYText'
  pod 'Masonry'
  pod 'YYCategories'

  
  #导入本地私有库
  pod 'LKUtils',                :path =>'./LKLib/LKUtils'
  pod 'LKUIDisplayModule',      :path =>'./LKLib/LKUIDisplayModule'

end
